[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
exclude = [
  ".git",
  ".venv",
  ".ruff_cache",
  ".devcontainer",
  "__pycache__",
  ".pytest_cache",
  ".github"
]

[tool.coverage.run]
source = ["lorrem"]
branch = true
command_line = "-m pytest"
data_file = ".coverage"

[tool.coverage.report]
fail_under = 80
skip_empty = true
skip_covered = true
sort = "-Cover"
show_missing = true

[tool.pytest.ini_options]
testpaths = [
  "tests",
]
